name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions ðŸš€
on:
  push:
    branches: [main, develop]

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        hostname: [CONfI, SECRET]
    steps:
      - name: test secret
        run: |
          echo "TESTING...."
          echo ${{ secrets[format('{0}_PASSWORD', matrix.hostname )] }}
          echo ${{ secrets[format('{0}_USERNAME', matrix.hostname )] }}
